export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'; 
export const FILTER_PRODUCTS_BY_STYLE = 'FILTER_PRODUCTS_BY_STYLE';
export const SORT_PRODUCTS_BY_PRICE = 'SORT_PRODUCTS_BY_PRICE'; 
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'; 